/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import java.io.FileNotFoundException;
import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;

/**
 *
 * @author Александр
 */

public class Mainframe extends javax.swing.JFrame {
    

    /**
     * Creates new form Mainframe
     */
    public Mainframe() {
        initComponents();
        jPanel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Record = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tProductCode1 = new javax.swing.JTextField();
        lPrice1 = new javax.swing.JLabel();
        lProductcode1 = new javax.swing.JLabel();
        tPrice1 = new javax.swing.JTextField();
        tStockNumber1 = new javax.swing.JTextField();
        tProductName1 = new javax.swing.JTextField();
        lProductName1 = new javax.swing.JLabel();
        tArrivalDate1 = new javax.swing.JTextField();
        lArrivalDate1 = new javax.swing.JLabel();
        lStoragePeriod1 = new javax.swing.JLabel();
        tStoragePeriod1 = new javax.swing.JTextField();
        lNumber1 = new javax.swing.JLabel();
        lStock1 = new javax.swing.JLabel();
        tNumber1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Information = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tProductCode = new javax.swing.JTextField();
        lPrice = new javax.swing.JLabel();
        lProductcode = new javax.swing.JLabel();
        tPrice = new javax.swing.JTextField();
        tStockNumber = new javax.swing.JTextField();
        tProductName = new javax.swing.JTextField();
        lProductName = new javax.swing.JLabel();
        tArrivalDate = new javax.swing.JTextField();
        lArrivalDate = new javax.swing.JLabel();
        lStoragePeriod = new javax.swing.JLabel();
        tStoragePeriod = new javax.swing.JTextField();
        lNumber = new javax.swing.JLabel();
        lStock = new javax.swing.JLabel();
        tNumber = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tRecordnum = new javax.swing.JTextField();
        Info = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        Open = new javax.swing.JMenuItem();
        Close = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        Add = new javax.swing.JMenuItem();
        Clear = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        Record.setTitle("New Record");
        Record.setMinimumSize(new java.awt.Dimension(400, 450));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Добавление новой записи: ");

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lPrice1.setBackground(new java.awt.Color(0, 240, 240));
        lPrice1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        lPrice1.setText("Price");

        lProductcode1.setBackground(new java.awt.Color(0, 240, 240));
        lProductcode1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        lProductcode1.setText("Product code");

        tProductName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tProductName1ActionPerformed(evt);
            }
        });

        lProductName1.setBackground(new java.awt.Color(0, 240, 240));
        lProductName1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        lProductName1.setText("Product name");

        lArrivalDate1.setBackground(new java.awt.Color(0, 240, 240));
        lArrivalDate1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        lArrivalDate1.setText("Arrival date");

        lStoragePeriod1.setBackground(new java.awt.Color(0, 240, 240));
        lStoragePeriod1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        lStoragePeriod1.setText("Storage period");

        lNumber1.setBackground(new java.awt.Color(0, 240, 240));
        lNumber1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        lNumber1.setText("Number");

        lStock1.setBackground(new java.awt.Color(0, 240, 240));
        lStock1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        lStock1.setText("Stock #");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNumber1)
                    .addComponent(lStoragePeriod1)
                    .addComponent(lArrivalDate1)
                    .addComponent(lProductName1)
                    .addComponent(lProductcode1)
                    .addComponent(lStock1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPrice1))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tNumber1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tStoragePeriod1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tProductCode1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tStockNumber1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tProductName1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tArrivalDate1)
                    .addComponent(tPrice1))
                .addGap(0, 108, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lStock1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tStockNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lProductcode1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tProductCode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lProductName1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tProductName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lArrivalDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tArrivalDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lStoragePeriod1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tStoragePeriod1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Добавить");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Отмена");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RecordLayout = new javax.swing.GroupLayout(Record.getContentPane());
        Record.getContentPane().setLayout(RecordLayout);
        RecordLayout.setHorizontalGroup(
            RecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecordLayout.createSequentialGroup()
                .addGroup(RecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RecordLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RecordLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(RecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(RecordLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4)))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        RecordLayout.setVerticalGroup(
            RecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(RecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        Information.setTitle("О приложении");
        Information.setMinimumSize(new java.awt.Dimension(200, 200));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Версия приложения: 1.0");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Автор: Александр Валай");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel4.setText("Belarus, 2017");

        javax.swing.GroupLayout InformationLayout = new javax.swing.GroupLayout(Information.getContentPane());
        Information.getContentPane().setLayout(InformationLayout);
        InformationLayout.setHorizontalGroup(
            InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InformationLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4))
            .addGroup(InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(InformationLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        InformationLayout.setVerticalGroup(
            InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformationLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jLabel4))
            .addGroup(InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(InformationLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(133, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Магазин с товарами");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lPrice.setBackground(new java.awt.Color(0, 240, 240));
        lPrice.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        lPrice.setText("Price");

        lProductcode.setBackground(new java.awt.Color(0, 240, 240));
        lProductcode.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        lProductcode.setText("Product code");

        tProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tProductNameActionPerformed(evt);
            }
        });

        lProductName.setBackground(new java.awt.Color(0, 240, 240));
        lProductName.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        lProductName.setText("Product name");

        lArrivalDate.setBackground(new java.awt.Color(0, 240, 240));
        lArrivalDate.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        lArrivalDate.setText("Arrival date");

        lStoragePeriod.setBackground(new java.awt.Color(0, 240, 240));
        lStoragePeriod.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        lStoragePeriod.setText("Storage period");

        lNumber.setBackground(new java.awt.Color(0, 240, 240));
        lNumber.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        lNumber.setText("Number");

        lStock.setBackground(new java.awt.Color(0, 240, 240));
        lStock.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        lStock.setText("Stock #");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText(">");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Запись №");

        tRecordnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tRecordnumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tRecordnum, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lProductcode)
                    .addComponent(lStock, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lProductName)
                    .addComponent(lArrivalDate)
                    .addComponent(lStoragePeriod)
                    .addComponent(lNumber)
                    .addComponent(lPrice))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tArrivalDate)
                    .addComponent(tStoragePeriod)
                    .addComponent(tNumber)
                    .addComponent(tPrice)
                    .addComponent(tStockNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tProductCode)
                    .addComponent(tProductName))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lStock, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tStockNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lProductcode, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lArrivalDate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tArrivalDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tRecordnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lStoragePeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tStoragePeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        Info.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        File.setText("File");
        File.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FileMouseExited(evt);
            }
        });

        Open.setText("Open data");
        Open.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OpenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OpenMouseExited(evt);
            }
        });
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });
        File.add(Open);

        Close.setText("Close data");
        Close.setEnabled(false);
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseMouseExited(evt);
            }
        });
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        File.add(Close);

        jMenuBar1.add(File);

        Edit.setText("Edit");
        Edit.setEnabled(false);
        Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditMouseExited(evt);
            }
        });

        Add.setText("Add record");
        Add.setEnabled(false);
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddMouseExited(evt);
            }
        });
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        Edit.add(Add);

        Clear.setText("Clear");
        Clear.setEnabled(false);
        Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClearMouseExited(evt);
            }
        });
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        Edit.add(Clear);

        jMenuBar1.add(Edit);

        jMenu1.setText("Info");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMenu1MouseExited(evt);
            }
        });

        jMenuItem4.setText("About ");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuItem4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMenuItem4MouseExited(evt);
            }
        });
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(Info, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed
    private java.io.File fileData =  null; //new java.io.File("Shop.dat");
    
    long pos = -1;
    RandomAccessFile raf = null;
    
    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
        Open.setEnabled(false);
        Close.setEnabled(true);
        Edit.setEnabled(true);
        Add.setEnabled(true);
        Clear.setEnabled(true);
        javax.swing.JFileChooser file = new javax.swing.JFileChooser();
        file.setMultiSelectionEnabled( false );
        file.setSelectedFile( fileData );
        if ( file.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION ) {
            fileData = file.getSelectedFile();
            jPanel1.setVisible(true);
        }
        try {
            //flr = new FileReader(fileData.getAbsoluteFile());
            raf = new RandomAccessFile( fileData, "rw" );
            pos = raf.getFilePointer();
            if ( pos  < raf.length() ) {
                    boolean[] wasZipped = new boolean[] {false};
                    Object prodd = Buffer.readObject( raf, pos, wasZipped );
                    Product prod = (Product) prodd;
                    tProductName.setText(prod.productname);
                    tProductCode.setText(prod.productcode);
                    tStockNumber.setText("" + prod.stocknumber);
                    tStoragePeriod.setText("" + prod.storageperiod);
                    tArrivalDate.setText(prod.arrivaldate);
                    tNumber.setText("" + prod.number);
                    tPrice.setText(prod.price + "$");                    
                    tRecordnum.setText("" + (pos+1));
            }
        }
        catch(FileNotFoundException e){
            System.exit(1);
        }
        catch(Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ошибка чтения файла");
            Open.setEnabled(true);
            Close.setEnabled(false);
            jPanel1.setVisible(false);
            Edit.setEnabled(false);
            fileData = null;
            
        }
    }//GEN-LAST:event_OpenActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        Open.setEnabled(true);
        Close.setEnabled(false);
        jPanel1.setVisible(false);
        Edit.setEnabled(false);
        fileData = null;
        raf = null;
    }//GEN-LAST:event_CloseActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Information.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        fileData.delete();
        fileData = null;
        raf = null;
        pos = -1;
        Open.setEnabled(true);
        Close.setEnabled(false);
        jPanel1.setVisible(false);
        Edit.setEnabled(false);
        jPanel1.setVisible(false);
        
    }//GEN-LAST:event_ClearActionPerformed

    private void tRecordnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tRecordnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tRecordnumActionPerformed

    private void tProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tProductNameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            pos = raf.getFilePointer();
            if ( pos  < raf.length() ) {
                    boolean[] wasZipped = new boolean[] {false};
                    Object prodd = Buffer.readObject( raf, pos, wasZipped );
                    Product prod = (Product) prodd;
                    tProductName.setText(prod.productname);
                    tProductCode.setText(prod.productcode);
                    tStockNumber.setText("" + prod.stocknumber);
                    tStoragePeriod.setText("" + prod.storageperiod);
                    tArrivalDate.setText(prod.arrivaldate);
                    tNumber.setText("" + prod.number);
                    tPrice.setText(prod.price + "$");                    
                    tRecordnum.setText("" + (pos+1));
            }
            else{
                javax.swing.JOptionPane.showMessageDialog(this, "Достигнута последняя запись, возвращение в начало файла");
                raf.seek(0);
            }
        }
        catch(Exception  e){
            javax.swing.JOptionPane.showMessageDialog(this, "File Read Error");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        Record.setVisible(true);
    }//GEN-LAST:event_AddActionPerformed

    private void tProductName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tProductName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tProductName1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Product prod = new Product();
            prod.stocknumber = Integer.parseInt(tStockNumber1.getText());
            if(prod.stocknumber < 1)
                throw new IOException("Number of stocks should be >=1");
            prod.productcode = tProductCode1.getText();
            prod.productname = tProductName1.getText();
            prod.arrival = tArrivalDate1.getText();
            if ( ! Product.validDate(prod.arrival) ) {
                throw new IOException("Invalid Product.arrivaldate value");
            }
            prod.modifyDate();
            prod.storageperiod = Integer.parseInt(tStoragePeriod1.getText());
            if(prod.storageperiod < 0)
                throw new IOException("Invalid storage period value");
            prod.number = Integer.parseInt(tNumber1.getText());
            if(prod.number < 0)
                throw new IOException("Invalid number of products value");
            prod.price = Double.parseDouble(tPrice1.getText());
            if(prod.price < 0)
                throw new IOException("Invalid price value");
            Buffer.writeObject(raf, prod, false);
            tProductName1.setText("");
            tProductCode1.setText("");
            tStockNumber1.setText("");
            tStoragePeriod1.setText("");
            tArrivalDate1.setText("");
            tNumber1.setText("");
            tPrice1.setText("");                    
            Record.setVisible(false);
        }
        catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(this, "Ошибка добавления, причина:\n" + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Record.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void FileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FileMouseEntered
        // TODO add your handling code here:
        Info.setText("Меню открытия/закрытия файла");
        Info.repaint();
    }//GEN-LAST:event_FileMouseEntered

    private void FileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FileMouseExited
       Info.setText("");
       Info.repaint();
    }//GEN-LAST:event_FileMouseExited

    private void OpenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpenMouseEntered
       Info.setText("Открыть файл");
       Info.repaint();
    }//GEN-LAST:event_OpenMouseEntered

    private void OpenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpenMouseExited
       Info.setText("");
       Info.repaint();
    }//GEN-LAST:event_OpenMouseExited

    private void CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseEntered
       Info.setText("Закрыть файл");
       Info.repaint();
    }//GEN-LAST:event_CloseMouseEntered

    private void CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseExited
       Info.setText("");
       Info.repaint();
    }//GEN-LAST:event_CloseMouseExited

    private void EditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditMouseEntered
       Info.setText("Редактировать файл");
       Info.repaint();
    }//GEN-LAST:event_EditMouseEntered

    private void EditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditMouseExited
       Info.setText("");
       Info.repaint();
    }//GEN-LAST:event_EditMouseExited

    private void AddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseEntered
       Info.setText("Добавить новую запись");
       Info.repaint();
    }//GEN-LAST:event_AddMouseEntered

    private void AddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseExited
       Info.setText("");
       Info.repaint();
    }//GEN-LAST:event_AddMouseExited

    private void ClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearMouseEntered
       Info.setText("Очистить");
       Info.repaint();
    }//GEN-LAST:event_ClearMouseEntered

    private void ClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearMouseExited
       Info.setText("");
       Info.repaint();
    }//GEN-LAST:event_ClearMouseExited

    private void jMenu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseEntered
       Info.setText("Информация");
       Info.repaint();
    }//GEN-LAST:event_jMenu1MouseEntered

    private void jMenu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseExited
       Info.setText("");
       Info.repaint();
    }//GEN-LAST:event_jMenu1MouseExited

    private void jMenuItem4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem4MouseEntered
       Info.setText("О приложении");
       Info.repaint();
    }//GEN-LAST:event_jMenuItem4MouseEntered

    private void jMenuItem4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem4MouseExited
       Info.setText("");
       Info.repaint();
    }//GEN-LAST:event_jMenuItem4MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
       Info.setText("К следующей записи");
       Info.repaint();
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
       Info.setText("");
       Info.repaint();
    }//GEN-LAST:event_jButton2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainframe().setVisible(true);         
            }
        });
    }
    /*static void printFile()
            throws FileNotFoundException, IOException, ClassNotFoundException {
        long pos;
        int rec = 0;
        try ( RandomAccessFile raf = new RandomAccessFile( filename, "rw" )) {
            while (( pos = raf.getFilePointer()) < raf.length() ) {
                System.out.print( "#" + (++rec ));
                //printRecord( raf, pos );
            }
            System.out.flush();
        }
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Add;
    private javax.swing.JMenuItem Clear;
    private javax.swing.JMenuItem Close;
    private javax.swing.JMenu Edit;
    private javax.swing.JMenu File;
    private javax.swing.JLabel Info;
    private javax.swing.JDialog Information;
    private javax.swing.JMenuItem Open;
    private javax.swing.JDialog Record;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lArrivalDate;
    private javax.swing.JLabel lArrivalDate1;
    private javax.swing.JLabel lNumber;
    private javax.swing.JLabel lNumber1;
    private javax.swing.JLabel lPrice;
    private javax.swing.JLabel lPrice1;
    private javax.swing.JLabel lProductName;
    private javax.swing.JLabel lProductName1;
    private javax.swing.JLabel lProductcode;
    private javax.swing.JLabel lProductcode1;
    private javax.swing.JLabel lStock;
    private javax.swing.JLabel lStock1;
    private javax.swing.JLabel lStoragePeriod;
    private javax.swing.JLabel lStoragePeriod1;
    private javax.swing.JTextField tArrivalDate;
    private javax.swing.JTextField tArrivalDate1;
    private javax.swing.JTextField tNumber;
    private javax.swing.JTextField tNumber1;
    private javax.swing.JTextField tPrice;
    private javax.swing.JTextField tPrice1;
    private javax.swing.JTextField tProductCode;
    private javax.swing.JTextField tProductCode1;
    private javax.swing.JTextField tProductName;
    private javax.swing.JTextField tProductName1;
    private javax.swing.JTextField tRecordnum;
    private javax.swing.JTextField tStockNumber;
    private javax.swing.JTextField tStockNumber1;
    private javax.swing.JTextField tStoragePeriod;
    private javax.swing.JTextField tStoragePeriod1;
    // End of variables declaration//GEN-END:variables
}
